all:
	$(MAKE) -C GageAcquire all
	$(MAKE) -C GageCoerce all
	$(MAKE) -C GageComplexTrigger all
	$(MAKE) -C GageDeepAcquisition all
	$(MAKE) -C GageMultipleRecord all
	$(MAKE) -C GageMultipleSystem all
	$(MAKE) -C Advanced/GageEvents all
	$(MAKE) -C Advanced/GageCsPrf all
	$(MAKE) -C Advanced/GageStream2Analysis all
	$(MAKE) -C Advanced/GageStream2Disk all

#.PHONY : clean install uninstall
.PHONY : clean

clean:
	$(MAKE) -C GageAcquire clean
	$(MAKE) -C GageCoerce clean
	$(MAKE) -C GageComplexTrigger clean
	$(MAKE) -C GageDeepAcquisition clean
	$(MAKE) -C GageMultipleRecord clean
	$(MAKE) -C GageMultipleSystem clean
	$(MAKE) -C Advanced/GageEvents clean
	$(MAKE) -C Advanced/GageCsPrf clean
	$(MAKE) -C Advanced/GageStream2Analysis clean
	$(MAKE) -C Advanced/GageStream2Disk clean

#install:
#	$(MAKE) -C GageAcquire install
#	$(MAKE) -C GageCoerce install
#	$(MAKE) -C GageComplexTrigger install
#	$(MAKE) -C GageDeepAcquisition install
#	$(MAKE) -C GageMultipleRecord install
#	$(MAKE) -C GageMultipleSystem install
#	$(MAKE) -C Advanced/GageEvents install
#	$(MAKE) -C Advanced/GageCsPrf install
#	$(MAKE) -C Advanced/GageStream2Analysis install
#	$(MAKE) -C Advanced/GageStream2Disk install
#
#uninstall:
#	$(MAKE) -C GageAcquire uninstall
#	$(MAKE) -C GageCoerce uninstall
#	$(MAKE) -C GageComplexTrigger uninstall
#	$(MAKE) -C GageDeepAcquisition uninstall
#	$(MAKE) -C GageMultipleRecord uninstall
#	$(MAKE) -C GageMultipleSystem uninstall
#	$(MAKE) -C Advanced/GageEvents uninstall
#	$(MAKE) -C Advanced/GageCsPrf uninstall
#	$(MAKE) -C Advanced/GageStream2Analysis uninstall
#	$(MAKE) -C Advanced/GageStream2Disk uninstall
