#ifndef __CS_ERRORSTRUCT_H__
#define __CS_ERRORSTRUCT_H__

// This file is used only for Limux
#ifdef __linux__

typedef struct _ERROR_STRUCT
{
	int nErrorCode;
	char strText[180];
} ERRORSTRUCT, *PERRORSTRUCT;



ERRORSTRUCT g_arrErrorCodes[] =
{
	{0, "Unnecessary operation"},
	{1, "Sucessful Operation"},
	{2, "Configuration Coerced"},
	{3, "Asynchronous request succeeded"},
	{4, "MinMax detection: Segment Info queue is empty"},
	{-1, "Gage driver not initialized"},
	{-3, "Resource Manager unspecified failure"},
	{-4, "Resource Manager invalid interface"},
	{-5, "Handle already locked"},
	{-6, "Invalid handle"},
	{-7, "Invalid request parameter"},
	{-8, "No digitizer system found"},
	{-9, "Failed memory allocation"},
	{-10, "Lock system failed"},
	{-11, "Invalid structure size"},
	{-12, "Invalid action in current state"},
	{-13, "Invalid event type"},
	{-14, "Cannot create shared memory region"},
	{-15, "Invalid filename"},
	{-16, "Cannot map shared memory region"},
	{-17, "Invalid start address"},
	{-18, "Invalid length"},
	{-19, "Windows socket error"},
	{-20, "Resource Manager communication error"},
	{-21, "No digitizer system found with the requested requirements"},
	{-22, "Usage of NULL pointer"},
	{-23, "Invalid channel index"},
	{-24, "Invalid trigger index"},
	{-25, "Invalid event type"},
	{-26, "Buffer too small"},
	{-27, "Invalid parameter"},
	{-28, "Invalid sample rate"},
	{-29, "No external clock support"},
	{-30, "Mulrec : Invalid size or count"},
	{-31, "Invalid segment size"},
	{-32, "Depth greater than segment size"},
	{-33, "Invalid calibration mode"},
	{-34, "Invalid trigger condition"},
	{-35, "Invalid trigger level"},
	{-36, "Invalid trigger source"},
	{-37, "No external trigger support"},
	{-38, "Invalid acquisition mode"},
	{-39, "Invalid impedance"},
	{-40, "Invalid gain"},
	{-41, "Invalid coupling"},
	{-42, "Buffer not DWORD aligned"},
	{-43, "Pretrigger depth exceeds the maximum supported value"},
	{-44, "Invalid trigger depth (not multiple of depth resolution)"},
	{-45, "Invalid function"},
	{-46, "Timeout error"},
	{-47, "Invalid parameter ID"},
	{-48, "Invalid pointer"},
	{-49, "DMA: Buffer too big"},
	{-50, "Pending asynchronous operation"},
	{-51, "Invalid channel count"},
	{-52, "Invalid trigger count"},
	{-53, "Invalid segment"},
	{-54, "Invalid segment count"},
	{-55, "Invalid CapsID"},
	{-56, "Handle not in use"},
	{-57, "Kernel memory allocation failed"},
	{-58, "Invalid transfer mode"},
	{-59, "Asynchronous calls not supported"},
	{-60, "Too many trigger engines"},
	{-61, "Too many trigger masters"},
	{-62, "Pretrigger depth exceeds the maximum supported value"},
	{-63, "Invalid firmware version"},
	{-64, "Trigger Holdoff is invalid"},
	{-65, "Trigger Delay is invalid"},
	{-66, "Invalid Streaming buffer"},
	{-67, "Error HW FIFO overlow"},
	{-68, "Invalid card index"},
	{-69, "Invalid token for Asynchronous transfer"},
	{-70, "Discrepancies between Master and Slave boards"},
	{-71, "The mutiplier parameter of FIR structure is invalid"},
	{-72, "The MinMax driver internal queue is invalid"},
	{-73, "Cannot find a free trigger engine dedicated for channel or card"},
	{-74, "Mulrec raw data exeeds 4G bytes"},
	{-75, "Invalid filter value"},
	{-76, "Invalid DC offset"},
	{-77, "External clock frequency is not supported by this model"},
	{-78, "External clock signal is not present"},
	{-79, "Cannot reinitialize when systems are active"},
	{-80, "Channel Proctection Fault"},
	{-81, "Invalid number of average"},
	{-82, "Invalid time stamp clock"},
	{-83, "Asynchronous data transfer has been aborted"},
	{-84, "Circular buffer for streaming is not allocated"},
	{-85, "Error create file for streaming"},
	{-86, "Error write to stream file"},
	{-87, "Timeout on data transfer"},
	{-88, "DeviceIoControl request error"},
	{-89, "No more OVERLAPPED structure"},
	{-90, "CreateEvent error"},
	{-91, "Error on Flash state"},
	{-92, "Error on Flash cross boundary"},
	{-93, "Error on Flash Erase Sector"},
	{-94, "Flash operation is done on an invalid sector"},
	{-95, "Flash data read error"},
	{-96, "Flash data write error"},
	{-97, "cquisition system is  not initialized"},
	{-98, "Power State error. Please close then restart the application."},
	{-99, "Segment size exceeds the maximum supported value"},
	{-100, "Unrecognized firmware command"},
	{-101, "Nios timeout"},
	{-102, "Invalid DAC address"},
	{-103, "Invalid delay line edge"},
	{-104, "Invalid self test mode"},
	{-105, "Nios failed on reset"},
	{-106, "No system support for interrupts"},
	{-107, "Addon initialization failure"},
	{-108, "Invalid ADC address"},
	{-109, "Access to ADC failed"},
	{-110, "Access to Flash or Eeprom timeout"},
	{-111, "Error on the buffer address when reading/writting flash"},
	{-112, "Error on the buffer size when reading/writting flash"},
	{-113, "Error on the address of the flash"},
	{-114, "Error on erasing the flash sector"},
	{-120, "Invalid board count"},
	{-200, "Calibration DAC failure on voltage"},
	{-201, "Busy timeout in calibration sequence"},
	{-202, "Timing calibration failure"},
	{-203, "Coarse offset calibration failed on channel %d"},
	{-204, "Fine offset calibration failed on channel %d"},
	{-205, "Gain calibration failed on channel %d"},
	{-206, "Position calibration failed on channel %d"},
	{-207, "Calibration DAC is out of range"},
	{-208, "Failure to capture on calibration ADC"},
	{-209, "Failure to read reference ADC"},
	{-210, "Failure to read calibration ADC"},
	{-211, "Some channels are not calibrated"},
	{-212, "Master/Slave calibration failed"},
	{-213, "Ext Trigger calibration failed"},
	{-214, "DAC CalibTable in Eeprom is invalid"},
	{-215, "ADCs alignment calibration failed"},
	{-216, "Calibration source reference failed"},
	{-217, "Fast calibration failed"},
	{-218, "DPA of the ADC failed"},
	{-219, "Alignment of External trigger failed"},
	{-220, "Main PLL lost clock lock"},
	{-221, "Buffer for calibration is not allocated"},
	{-222, "Null offset calibration failed on channel %d"},
	{-223, "Intra core skew calibration failed on channel %d"},
	{-224, "Intra ADC skew calibration failed on channel %d"},
	{-225, "AC Calibration PLL lost clock lock"},
	{-226, "LVDS Alignement failed"},
	{-227, "DC Offset adjustment failed on channel %d"},
	{-228, "ADC I/Q Gain calibration failed"},
	{-229, "ADC I/Q Offset calibration failed"},
	{-230, "DC Level Freeze failed"},
	{-231, "Channel gain cross check boundary failed. (Exceed 1 db)"},
	{-300, "nvRam content is bad"},
	{-301, "FLASH content is bad"},
	{-302, "Eeprom content is bad"},
	{-303, "Addon board is not connected"},
	{-304, "Master/slave connector test has failed"},
	{-305, "Failed to determine the GIO access mode"},
	{-306, "Failed to load addon FPGA"},
	{-307, "Timeout when writting to eeprom"},
	{-407, "CompuScope information file is missing or corrupted"},
	{-411, "Invalid SIG file header"},
	{-412, "The PC needs to be shutdown then reboot after updated FW."},
	{-413, "Invalid Data Packing mode"},
	{-414, "Invalid depth for 8-bits data"},
	{-415, "Invalid segment size for 8-bits data"},
	{-416, "File open/create error."},
	{-800, "Stream transfer has been aborted"},
	{-801, "Stream Fifo overflow"}, 
	{-802, "Error on stream transfer size"}, 
	{-803, "Stream acquisition completed"},
	{-804, "Stream transfer timeout"},
	{-805, "Histogram full"},
	{-806, "The buffer for streaming is invalid"},
	{-807, "Error on DDC core configuration"},
	{-808, "Total data size of streaming acquisition is invalid"},
	{-850, "Remote instrument communication error"},
	{-32767, "Miscellaneous Error"},
};

#define g_arrErrorCodeSize sizeof(g_arrErrorCodes)/sizeof(ERRORSTRUCT)

#endif


#endif // __CS_ERRORSTRUCT_H__
