
#ifndef __CsBrainiacOptions_h__
#define __CsBrainiacOptions_h__

#define BRAIN_TRIGGER_RES				16

//!----- Default settings

#define BRAIN_DEFAULT_VALUE				0	
#define BRAIN_DEFAULT_RELATION			CS_RELATION_OR
#define BRAIN_DEFAULT_LEVEL				0

#define	BRAIN_MEMORY_CLOCK				150000000		// 150MHz clock
#define BRAIN_DAC_SETTLE_DELAY			5

#define	BRAIN_DEFAULT_MSTRIGMODE			3
#define BRAIN_DEFAULT_TRIG_SENSITIVITY	6
#define BRAIN_DEFAULT_SAMPLE_RATE		-1				// Force to the default sampling rate depending on card
#define BRAIN_DEFAULT_EXT_CLOCK_EN		0
#define BRAIN_DEFAULT_MODE				CS_MODE_SINGLE
#define BRAIN_DEFAULT_SAMPLE_BITS		CS_SAMPLE_BITS_12
#define BRAIN_DEFAULT_RES				(-1*CS_SAMPLE_RES_8)
#define BRAIN_DEFAULT_SAMPLE_SIZE		CS_SAMPLE_SIZE_2
#define BRAIN_DEFAULT_SAMPLE_OFFSET		CS_SAMPLE_OFFSET_UNSIGN_8
#define BRAIN_DEFAULT_SEGMENT_COUNT		1
#define BRAIN_DEFAULT_DEPTH				8192
#define BRAIN_DEFAULT_SEGMENT_SIZE		BRAIN_DEFAULT_DEPTH
#define BRAIN_DEFAULT_TRIG_TIME_OUT		-1
#define BRAIN_DEFAULT_TRIG_ENGINES_EN	CS_TRIG_ENGINES_DIS
#define BRAIN_DEFAULT_TRIG_HOLD_OFF		0
#define BRAIN_DEFAULT_TRIG_DELAY			0

#define BRAIN_DEFAULT_CHANNEL_INDEX		0
#define BRAIN_DEFAULT_TERM				CS_COUPLING_DC
#define BRAIN_DEFAULT_GAIN				360		//	360 mv pk-pk
#define BRAIN_DEFAULT_IMPEDANCE			CS_REAL_IMP_50_OHM
#define BRAIN_DEFAULT_FILTER			0
#define BRAIN_DEFAULT_POSITION			0

#define BRAIN_DEFAULT_CONDITION			CS_TRIG_COND_POS_SLOPE
#define BRAIN_DEFAULT_SOURCE			CS_CHAN_1
#define BRAIN_DEFAULT_EXT_COUPLING		CS_COUPLING_DC
#define BRAIN_DEFAULT_EXT_GAIN			CS_GAIN_10_V
#define BRAIN_DEFAULT_EXT_IMPEDANCE		CS_REAL_IMP_1M_OHM

#define BRAIN_DEFAULT_EXT_COUPLING		CS_COUPLING_DC
#define BRAIN_DEFAULT_EXT_GAIN			CS_GAIN_10_V
#define BRAIN_DEFAULT_EXT_IMPEDANCE		CS_REAL_IMP_1M_OHM



//
//		 EEPROM OPTIONS
//

// "Base board" options
#define BRAIN_OPT_NOMEMORY			0x1


// "Addon" options
#define BRAIN_OPT_DUAL_CHANNEL		0x1



// Base board options that require Special Firmware
#define	BRAIN_BBHW_OPT_FWREQUIRED_MASK		BRAIN_OPT_NOMEMORY


// Addon board options that require Special Firmware
#define	BRAIN_AOHW_OPT_FWREQUIRED_MASK		0



#endif