#ifndef __CsDeereOptions_h__
#define __CsDeereOptions_h__


#define DEERE_DEFAULT_VALUE				0	
#define DEERE_DEFAULT_RELATION			CS_RELATION_OR
#define DEERE_DEFAULT_LEVEL				0

#define	DEERE_MEMORY_CLOCK				137500000		// 137.5MHz clock

#define	DEERE_DEFAULT_MSTRIGMODE		3
#define DEERE_DEFAULT_TRIG_SENSITIVITY	0x9D
#define DEERE_DEFAULT_EXT_TRIG_SENSITIVITY 50          //±5%
#define DEERE_DEFAULT_SAMPLE_RATE		-1				// Force to the default sampling rate depending on card
#define DEERE_DEFAULT_EXT_CLOCK_EN		0
#define DEERE_DEFAULT_MODE				CS_MODE_DUAL
#define DEERE_DEFAULT_SAMPLE_BITS		CS_SAMPLE_BITS_12
#define DEERE_DEFAULT_RES				-CS_SAMPLE_RES_LJ
#define DEERE_DEFAULT_SAMPLE_SIZE		CS_SAMPLE_SIZE_2
#define DEERE_DEFAULT_SAMPLE_OFFSET		CS_SAMPLE_OFFSET_12_LJ
#define DEERE_DEFAULT_SEGMENT_COUNT		1
#define DEERE_DEFAULT_DEPTH				8192
#define DEERE_DEFAULT_SEGMENT_SIZE		DEERE_DEFAULT_DEPTH
#define DEERE_DEFAULT_TRIG_TIME_OUT		-1
#define DEERE_DEFAULT_TRIG_ENGINES_EN	CS_TRIG_ENGINES_DIS
#define DEERE_DEFAULT_TRIG_HOLD_OFF		0
#define DEERE_DEFAULT_TRIG_DELAY		0
#define DEERE_DEFAULT_CLOCK_OUT			CS_OUT_NONE //	eclkoNone 


#define DEERE_DEFAULT_CHANNEL_INDEX		0
#define DEERE_DEFAULT_TERM				CS_COUPLING_DC
#define DEERE_DEFAULT_IMPEDANCE			CS_REAL_IMP_50_OHM
#define DEERE_DEFAULT_FILTER			0
#define DEERE_DEFAULT_POSITION			0

#define DEERE_DEFAULT_CONDITION			CS_TRIG_COND_POS_SLOPE
#define DEERE_DEFAULT_SOURCE			CS_CHAN_1

#define DEERE_USER_OFFSET_LIMIT         250

// "Base board" options
#define	DEERE_OPT_SQUAREMULREC		0x1

// "Addon" options
#define DEERE_OPT_DUAL_CHANNEL		0x1
#define	DEERE_OPT_14BIT				0x2
#define	DEERE_OPT_2ADC				0x4
#define	DEERE_OPT_4ADC				0x8
#define	DEERE_OPT_AUX_IO			0x10
#define	DEERE_OPT_LOW_CALIB_FREQ	0x20


// Base board options that require Special Firmware
#define	DEERE_BBHW_OPT_FWREQUIRED_MASK		0

// Addon board options that require Special Firmware
#define	DEERE_AOHW_OPT_FWREQUIRED_MASK		0


#endif