#include <windows.h>

#define IDD_AUX_IO_DLG                  200

#define VER_FILEFLAGSMASK			VS_FFI_FILEFLAGSMASK
#define VER_FILEOS          		VOS_NT_WINDOWS32

#ifdef _DEBUG
	#define VER_FILEFLAGS				1
#else
	#define VER_FILEFLAGS				0
#endif



#define VER_PRODUCTNAME_STR 		"CompuScope driver"
#define VER_COMPANYNAME_STR 		"Gage Applied Technologies"
#define VER_LEGALCOPYRIGHT_YEARS    	" 2003 - 2014"
#define VER_LEGALCOPYRIGHT_STR		"(c) " VER_COMPANYNAME_STR VER_LEGALCOPYRIGHT_YEARS
#define VER_LEGALTRADEMARKS_STR     	""
#define VER_PRODUCTVERSION		05,02,00,00
#define VER_PRODUCTVERSION_STR		"5, 02, 00, 0"
#define VER_FILEVERSION			VER_PRODUCTVERSION
#define VER_FILEVERSION_STR		VER_PRODUCTVERSION_STR
#define VER_PRODUCTVERSION_DW       	(0x01000000 | VER_PRODUCTBUILD)

#define VER_FILETYPE				VFT_DRV
#define VER_FILESUBTYPE				VFT2_DRV_SYSTEM


#define VER_PRODUCTNAME_LABVIEWSDK_STR		"CompuScope LabVIEW SDK"
#define VER_PRODUCTVERSION_LABVIEWSDK		05,02,00,00
#define VER_PRODUCTVERSION_LABVIEWSDK_STR	"5.02.00"

#define VER_PRODUCTNAME_MATLABSDK_STR		"CompuScope MATLAB SDK"
#define VER_PRODUCTVERSION_MATLABSDK		05,02,00,00
#define VER_PRODUCTVERSION_MATLABSDK_STR	"5.02.00"

#define VER_PRODUCTNAME_CSDK_STR			"CompuScope C/C# SDK"
#define VER_PRODUCTVERSION_CSDK				05,00,00,00
#define VER_PRODUCTVERSION_CSDK_STR			"5.00.00"
